- name: Blacklist nouveau mod
  file:
    src: nvidia-installer-disable-nouveau.conf
    dest: /etc/modprobe.d/nvidia-installer-disable-nouveau.conf
    mode: '0644'
    owner: root
    group: root

- name: Reboot for mod blacklist to take effect
  reboot:
    reboot_timeout: 1800

- stat:
    path: /lib/modules/4.15.0-72-generic/kernel/drivers/video/nvidia-drm.ko
  register: nvidia_mod

- name: Retrieve driver
  get_url:
    url: {{ nvidia_driver_url }}
    dest: /tmp/nvidia_driver.run
    mode: 777
  when: not nvidia_mod.stat.exists

- name: Install driver
  command: /bin/bash /tmp/nvidia_driver.run -s
  when: not nvidia_mod.stat.exists