---

- name: Check current state
  block:
    - stat:
        path: /etc/modprobe.d/nvidia-installer-disable-nouveau.conf
      register: mod_blacklisted
    - stat:
        path: /lib/modules/4.15.0-72-generic/kernel/drivers/video/nvidia-drm.ko
      register: nvidia_mod
    - stat:
        path: /usr/local/cuda
      register: cuda_toolkit

- name: Blacklist nouveau module
  block:
    - name: Blacklist nouveau mod
      copy:
        src: nvidia-installer-disable-nouveau.conf
        dest: /etc/modprobe.d/nvidia-installer-disable-nouveau.conf
        mode: '0644'
        owner: root
        group: root
    - name: Reboot for mod blacklist to take effect
      command: shutdown -r now
      async: 0
      poll: 0
    - name: Wait for server to come back
      wait_for_connection:
        timeout: 900
  when:
    - not mod_blacklisted.stat.exists

- name: Install GPU driver
  block:
    - name: Retrieve driver
      get_url:
        url: "{{ nvidia_driver_url }}"
        dest: /var/cuda/nvidia_driver.run
        mode: '0777'
    - name: Install driver
      command: /bin/bash /var/cuda/nvidia_driver.run -s
  when: not nvidia_mod.stat.exists

- name: Make sure install temp directory exists
  file:
    path: "{{ cuda_install_temp_directory }}"
    state: directory
    owner: root
    group: root
    mode: '0777'

- name: Install CUDA toolkit and patches
  command: "/bin/bash {{ item }} --tmpdir={{ cuda_install_temp_directory }} --silent"
  with_items: "{{ cuda_toolkit_paths }}"
  when: not cuda_toolkit.stat.exists

- name: Install CuDNN libraries and run-times
  command: "apt install -y {{ cudnn_library_paths | join(' ') }}"
