---

- name: Check current state
  block:
    - stat:
        path: /etc/modprobe.d/nvidia-installer-disable-nouveau.conf
      register: mod_blacklisted
    - stat:
        path: /lib/modules/4.15.0-72-generic/kernel/drivers/video/nvidia-drm.ko
      register: nvidia_mod
    - stat:
        path: /usr/local/cuda
      register: cuda_toolkit

- name: Blacklist nouveau module
  block:
    - name: Blacklist nouveau mod
      copy:
        src: nvidia-installer-disable-nouveau.conf
        dest: /etc/modprobe.d/nvidia-installer-disable-nouveau.conf
        mode: '0644'
        owner: root
        group: root
    - name: Reboot for mod blacklist to take effect
      reboot:
        reboot_timeout: 360
  when:
    - not mod_blacklisted.stat.exists

- name: Install Cuda repository pkg
  apt:
    deb: "{{ cuda_library_directory }}/10.0/cuda-repo-ubuntu1804_10.0.130-1_amd64.deb"

- name: Install apt key
  apt_key:
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
    state: present

- name: Install CUDA/NVidia packages
  apt:
    name:
      - cuda-10-0
      - cuda-demo-suite-10-0
      - cuda-runtime-10-0
      - libcuda1-340
      - libcuda1-340-updates
      - nvidia-utils-440
      - cuda-drivers
    update_cache: yes
    state: present

- name: Install CuDNN Library
  apt:
    deb: "{{ cuda_library_directory }}/libcudnn7_7.5.0.56-1+cuda10.0_amd64.deb"

- name: Install CuDNN Dev Library
  apt:
    deb: "{{ cuda_library_directory }}/libcudnn7-dev_7.5.0.56-1+cuda10.0_amd64.deb"
